### ISSUE TITLE
Support merging from multiple controllers

### ISSUE THREAD

**Issue by k-yle** [k-yle/sACN#2]
if the `priority` value is the same from two senders, the DMX slot data needs to be merged. [ETC's implementation](https://github.com/etcLabs/sACNMergeLib) could be used.

**Comment by hansSchall** [comment]
I would suggest to implement this in its own class.
Like this:

````ts
class ReceiverMerge extends Receiver{
    contructor(...){
        super(...);
        super.on("packet",this.mergePacket);
    }
    mergePacket(packet: Packet){
        // merge
    }
}
````

I'm currently working on a project where this feature might be usefull.
I will try to code this the next days.

**Comment by samkearney** [comment]
+1 for adding a "merge receiver" layer on top of a basic receiver. This is the approach we (ETC) use in [our C implementation](https://github.com/ETCLabs/sACN). [docs](https://etclabs.github.io/sACNDocs/2.0.1/using_merge_receiver.html)

**Comment by hansSchall** [comment]
Thats what I coded so far:
There might be minor bugs. Haven't tested this much. But it *should* work.

https://gist.github.com/hansSchall/e30c980d638ba239a15a752383b1a365

I will be able test it on Sunday.
