### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by lyndonbuckley** [k-yle/sACN#27]
Hey @k-yle,

![Screen Shot 2020-10-16 at 11 42 05 am](https://user-images.githubusercontent.com/3122733/96200170-f8e8ed80-0fa4-11eb-8f7b-9be3cf06c6a6.png)

Tried to send you email but it bounced. Is there a better way to contact you?

Lyndon

**Comment by k-yle** [comment]
Hi @lyndonbuckley, feel free to use k.y.l.e@outlook.co.nz
