### ISSUE TITLE
Unicast to a single IP?

### ISSUE THREAD

**Issue by waltsatan** [k-yle/sACN#52]
Is it possible to specify a single IP to send sACN data to?

**Comment by k-yle** [comment]
at the moment this isn't possible, but it seems like a reasonable request. the spec requires receivers to accept unicast data, and senders are permitted to send data to unicast addresses

**Comment by k-yle** [comment]
this is now supported as of `v4.4.0` using a new option `useUnicastDestination`:

```ts
const sACNServer = new Sender({
  universe: 1,
  useUnicastDestination: '10.51.0.8'
});
```

**Comment by waltsatan** [comment]
Amazing! Thank you. I'll give it a go with my Advatek on Monday.
