### ISSUE TITLE
Send data to multiple universes

### ISSUE THREAD

**Issue by highlyinteractive** [k-yle/sACN#56]
I notice you can only have one universe on the sender.

Is there a recommended way to send data to multiple universes?

**Comment by k-yle** [comment]
Hey, the current approach is to create one `Sender` class per universe, a bit like this: 

https://github.com/k-yle/sACN/blob/bfe007ab100386dc7bb4f932a88d0e83d5ea02b7/test/integration.test.ts#L15-L16

**Comment by highlyinteractive** [comment]
Great, that makes sense. Thanks
